//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpdateringAfDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Afsluttede_pladser
    {
        public int Id { get; set; }
        public string Sagsnummer { get; set; }
        public string Pladsnummer { get; set; }
    
        public virtual Pladser Pladser { get; set; }
        public virtual Sager Sager { get; set; }
    }
}
