//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpdateringAfDatabase
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BifaldEntities : DbContext
    {
        public BifaldEntities()
            : base("name=BifaldEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Afsluttede_pladser> Afsluttede_pladser { get; set; }
        public DbSet<Kasser> Kasser { get; set; }
        public DbSet<Kunder> Kunder { get; set; }
        public DbSet<Pladser> Pladser { get; set; }
        public DbSet<Sager> Sager { get; set; }
        public DbSet<Plads_historik> Plads_historik { get; set; }
    }
}
