//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpdateringAfDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kasser
    {
        public int Id { get; set; }
        public string Sagsnummer { get; set; }
        public int Antal { get; set; }
        public string Hentet_leveret { get; set; }
        public System.DateTime Hentet_leveret_dato { get; set; }
    
        public virtual Sager Sager { get; set; }
    }
}
