//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpdateringAfDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pladser
    {
        public Pladser()
        {
            this.Afsluttede_pladser = new HashSet<Afsluttede_pladser>();
            this.Plads_historik = new HashSet<Plads_historik>();
        }
    
        public string Pladsnummer { get; set; }
        public string Sagsnummer { get; set; }
        public string Type { get; set; }
    
        public virtual ICollection<Afsluttede_pladser> Afsluttede_pladser { get; set; }
        public virtual Sager Sager { get; set; }
        public virtual ICollection<Plads_historik> Plads_historik { get; set; }
    }
}
