//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpdateringAfDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sager
    {
        public Sager()
        {
            this.Afsluttede_pladser = new HashSet<Afsluttede_pladser>();
            this.Kasser = new HashSet<Kasser>();
            this.Pladser = new HashSet<Pladser>();
            this.Plads_historik = new HashSet<Plads_historik>();
        }
    
        public string Sagsnummer { get; set; }
        public int KundeId { get; set; }
        public System.DateTime Opbevaring_startdato { get; set; }
        public Nullable<System.DateTime> Opbevaring_slutdato { get; set; }
        public bool Afsluttet { get; set; }
        public string Noter { get; set; }
    
        public virtual ICollection<Afsluttede_pladser> Afsluttede_pladser { get; set; }
        public virtual ICollection<Kasser> Kasser { get; set; }
        public virtual Kunder Kunder { get; set; }
        public virtual ICollection<Pladser> Pladser { get; set; }
        public virtual ICollection<Plads_historik> Plads_historik { get; set; }
    }
}
