//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bifald.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DatabaseEntities : DbContext
    {
        public DatabaseEntities()
            : base("name=DatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Afsluttede_pladser> Afsluttede_pladser { get; set; }
        public virtual DbSet<Kunder> Kunder { get; set; }
        public virtual DbSet<Pladser> Pladser { get; set; }
        public virtual DbSet<Sager> Sager { get; set; }
        public virtual DbSet<Kasser> Kasser { get; set; }
    }
}
