//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bifald.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pladser
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pladser()
        {
            this.Afsluttede_pladser = new HashSet<Afsluttede_pladser>();
            this.Plads_historik = new HashSet<Plads_historik>();
        }
    
        public string Pladsnummer { get; set; }
        public string Sagsnummer { get; set; }
        public string Type { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Afsluttede_pladser> Afsluttede_pladser { get; set; }
        public virtual Sager Sager { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Plads_historik> Plads_historik { get; set; }
    }
}
