//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bifald.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Plads_historik
    {
        public int ID { get; set; }
        public string Sagsnummer { get; set; }
        public string Pladsnummer { get; set; }
        public string Opret_afslut { get; set; }
        public System.DateTime Dato { get; set; }
    
        public virtual Sager Sager { get; set; }
        public virtual Pladser Pladser { get; set; }
    }
}
